---
# This playbook is for provisioning on a Linode box. It should be at least a Linode 24576 box and have
# 64 bit Ubuntu 16.04 LTS with 256 MB swap.
#
# To run in development:
# vagrant provision local
#
# To run in production:
# cd provisioning
# ansible-playbook --user=root -i hosts playbook.yml
#

# Ubuntu 16.04 LTS doesn't come with python pre-installed. We need that for
# Ansible to work (for the gather facts). So install python first
- hosts: all
  become: true
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: all
  become: true
  pre_tasks:
    - name: Upgrade all packages first
      apt:
        update_cache: yes
        cache_valid_time: 300
        upgrade: yes
  roles:
    - morph-app
    - discourse
